--db: tienda_app
--schema:

/**************
 Table: ESTADOS_PEDIDO
 ***************/
CREATE TABLE MULTI_NIVEL.ESTADO_PEDIDO (
    ID SERIAL NOT NULL,
    DESCRIPCION VARCHAR(10) NOT NULL
);

ALTER TABLE
    MULTI_NIVEL.ESTADO_PEDIDO
ADD
    CONSTRAINT PK_ESTADOS_PEDIDO PRIMARY KEY(ID);

/**************
 Table: ESTADOS_PEDIDO
 ***************/
CREATE TABLE MULTI_NIVEL.CATEGORIA (
    ID SERIAL NOT NULL,
    NOMBRE VARCHAR(10) NOT NULL,
    DESCRIPCION VARCHAR(255) NULL
);

ALTER TABLE
    MULTI_NIVEL.CATEGORIA
ADD
    CONSTRAINT PK_CATEGORIA PRIMARY KEY(ID);

/**************
 Table: TIPO_DOCUMENTO
 ***************/
CREATE TABLE MULTI_NIVEL.TIPO_DOCUMENTO (
    ID SERIAL NOT NULL,
    DESCRIPCION VARCHAR(10) NOT NULL
);

ALTER TABLE
    MULTI_NIVEL.TIPO_DOCUMENTO
ADD
    CONSTRAINT PK_TIPO_DOCUMENTO PRIMARY KEY(ID);

/**************
 Table: CLIENTE
 ***************/
CREATE TABLE MULTI_NIVEL.CLIENTE (
    ID SERIAL NOT NULL,
    NOMBRES VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(50) NOT NULL,
    DOCUMENTO VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(1) NOT NULL,
    TIPO_ID INTEGER NOT NULL
);

ALTER TABLE
    MULTI_NIVEL.CLIENTE
ADD
    CONSTRAINT PK_CLIENTE PRIMARY KEY(ID);

ALTER TABLE
    MULTI_NIVEL.CLIENTE
ADD
    CONSTRAINT FK_CLIENTE_TIPO_DOC FOREIGN KEY(ID) REFERENCES MULTI_NIVEL.TIPO_DOCUMENTO(ID);

/**************
 Table: PRODUCTO
 ***************/
CREATE TABLE MULTI_NIVEL.PRODUCTO (
    ID SERIAL NOT NULL,
    REFERENCIA VARCHAR(10) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(255) NULL,
    PRECIO_UNITARIO NUMERIC(19, 2) NOT NULL,
    UNIDADES_DISPONIBLES NUMERIC(19, 2) NOT NULL,
    CATE_ID INTEGER NOT NULL
);

ALTER TABLE
    MULTI_NIVEL.PRODUCTO
ADD
    CONSTRAINT PK_PRODUCTO PRIMARY KEY(ID);

ALTER TABLE
    MULTI_NIVEL.PRODUCTO
ADD
    CONSTRAINT FK_PRODUCTO_CATE FOREIGN KEY(ID) REFERENCES MULTI_NIVEL.CATEGORIA(ID);

/**************
 Table: PEDIDO
 ***************/
CREATE TABLE MULTI_NIVEL.PEDIDO (
    ID SERIAL NOT NULL,
    FECHA TIMESTAMP NOT NULL,
    TOTAL NUMERIC(19, 2) NOT NULL,
    CLIE_ID INTEGER NOT NULL,
    ESPE_ID INTEGER NOT NULL
);

ALTER TABLE
    MULTI_NIVEL.PEDIDO
ADD
    CONSTRAINT PK_PEDIDO PRIMARY KEY(ID);

ALTER TABLE
   MULTI_NIVEL.PEDIDO
ADD
    CONSTRAINT FK_PEDIDO_CLIE FOREIGN KEY(ID) REFERENCES MULTI_NIVEL.CLIENTE(ID);

ALTER TABLE
    MULTI_NIVEL.PEDIDO
ADD
    CONSTRAINT FK_PEDIDO_ESPE FOREIGN KEY(ID) REFERENCES MULTI_NIVEL.ESTADO_PEDIDO(ID);

/**************
 Table: DETALLE_PEDIDO
 ***************/
CREATE TABLE MULTI_NIVEL.DETALLE_PEDIDO (
    ID SERIAL NOT NULL,
    CANTIDAD NUMERIC(19, 2) NOT NULL,
    VALOR NUMERIC(19, 2) NOT NULL,
    PEDI_ID INTEGER NOT NULL,
    PROD_ID INTEGER NOT NULL
);

ALTER TABLE
    MULTI_NIVEL.DETALLE_PEDIDO
ADD
    CONSTRAINT PK_DETALLE_PEDIDO PRIMARY KEY(ID);

ALTER TABLE
    MULTI_NIVEL.DETALLE_PEDIDO
ADD
    CONSTRAINT FK_DEPE_PEDI FOREIGN KEY(ID) REFERENCES MULTI_NIVEL.PEDIDO(ID);

ALTER TABLE
    MULTI_NIVEL.DETALLE_PEDIDO
ADD
    CONSTRAINT FK_DEPE_PROD FOREIGN KEY(ID) REFERENCES MULTI_NIVEL.PRODUCTO(ID);




/**************************************
INSERTS
**************************************/
INSERT INTO MULTI_NIVEL.CATEGORIA(NOMBRE, DESCRIPCION) VALUES('COMPUTADOR', 'PRODUCTOS DE COMPUTADORAS');
INSERT INTO MULTI_NIVEL.CATEGORIA(NOMBRE, DESCRIPCION) VALUES('CELULARES', 'PRODUCTOS DE CELULARES');

INSERT INTO MULTI_NIVEL.TIPO_DOCUMENTO(DESCRIPCION) VALUES('CC');
INSERT INTO MULTI_NIVEL.TIPO_DOCUMENTO(DESCRIPCION) VALUES('CE');
INSERT INTO MULTI_NIVEL.TIPO_DOCUMENTO(DESCRIPCION) VALUES('PA');

INSERT INTO MULTI_NIVEL.ESTADO_PEDIDO(DESCRIPCION) VALUES('P');
INSERT INTO MULTI_NIVEL.ESTADO_PEDIDO(DESCRIPCION) VALUES('D');
INSERT INTO MULTI_NIVEL.ESTADO_PEDIDO(DESCRIPCION) VALUES('E');